 const data=[
   {
    id:'1'  ,
    que: 'What is the Virtual DOM?' ,
    ans:'The virtual DOM is an in-memory representation of the real DOM elements generated by React components before any changes are made to the page.'
   },
   {
    id:'2'  ,
    que:'How do you create react app?' ,
    ans:'Create React App is a comfortable environment for learning React, and is the best way to start building a new single-page application in React.'
   },
   {
    id:'3',
    que: 'How do you create react app?' ,
    ans:'Create React App is a comfortable environment for learning React, and is the best way to start building a new single-page application in React.'
   },
   {
    id:"4",
    que:'What are components in react?',
    ans:'React components let you break up the user interface into separate pieces that can then be reused and handled independently. '
   }
]

export default data;